# Generated by Django 4.1.5 on 2023-01-17 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instances',
            name='users',
        ),
        migrations.AddField(
            model_name='instances',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
